### ISSUE TITLE
failed to select a version for `libsqlite3-sys`

### ISSUE THREAD

**Issue by doronnac** [tracel-ai/models#51]
**Describe the bug**

Hi, I'm creating an application which uses rusqlite and also would like to use burn.
However, using bert-burn and rusqlite causes the error in the title.

**To Reproduce**

git clone git@github.com:tracel-ai/models.git
cd models/bert-burn && cargo add rusqlite

**Additional context**
I've tried the fixes suggested in other issues, none worked.

**Comment by laggui** [comment]
There seems to be a conflict in the dependencies.

```toml
burn = { version = "0.14", default-features = false, features = ["dataset", "std"] }
burn-import = "0.13"
```

burn version is set to 0.14 but burn-import to 0.13. Looks like burn-import isn't even used. If you remove that it should work.

Was gonna submit a PR but stumbled on another issue so I'll figure this out first.

**Comment by laggui** [comment]
Ha thanks for flagging this so quickly 😄 

Forgot to commit something I had locally in the linked PR specifically for that. There is a missing feature flag in cubecl when burn 0.15 default features are disabled.

```toml
burn = { version = "0.15", default-features = false, features = ["dataset", "std"] }
cubecl-runtime = { version = "0.3.0", features = ["channel-mpsc"] } # missing feature flag when burn default-features are off
```
